### ISSUE TITLE
Just saying hi

### ISSUE THREAD

**Issue by billytunin** [Same-Page/front-and-back#22]
Hi @Arch1tect !
I came across your Chrome Extension because I had the very same idea and wondered if anybody ever developed something similar. I see you are developing something exactly as I pictured it in my head. So, first off, I congratulate you because I've been using the extension so far... and though it obviously still needs a lot of polishing, it's pretty neat!
Secondly, if you need a hand... let me know. I see that most of your UI and messages are Chinese. I'm from Argentina so I mainly speak Spanish. But I'm pretty fluent with English too. I could help you out with translations. And I've been a front-end developer for 5 years now.
I tried to clone this repo and run the app locally but had some problems. I dropped the idea because I'm kinda busy with work. But if you do want me to help or maybe just chat about the idea, let me know. You can contact me at gastonavigliano@gmail.com .

Cheers!

**Comment by Archi-tech** [comment]
Hi @billytunin !
Sounds awesome, yeah, I'm still improving this project, not only for chrome extension but also for website owners to embed it into their websites. I live in US, the code and comments are all written in English, some UI are in Chinese because most users are Chinese at the moment. I'm actively rewriting the whole project for the past two weeks since the code was quite messy which is hard for others to fork or contribute. It should be much easier to work with soon and I'll keep you posted once that's done.

Cheers!

**Comment by billytunin** [comment]
Cool! Glad to hear that.
Sure, let me know if anything.
Do you mind dropping any e-mail at which I could contact you in the future if necessary? Just saying because I can't send private messages here in Github haha. We can then delete this issue, if you want to keep your (and my) e-mail private.
If you prefer not to, that's fine too! I'll just create another issue in this repo in case I wish to contact you again in the future or something.

Cheers

**Comment by billytunin** [comment]
Closing this one out!
